<?xml version="1.0" encoding="utf-8"?><Database Name="karate" Class="KarateClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=D:\Documents\Source\Repository\KarateSchoolManager\karate.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="KarateSchoolManager.My.MySettings" SettingsPropertyName="karateConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Instructors" Member="Instructors">
    <Type Name="Instructor">
      <Column Name="ID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Members" Member="Members">
    <Type Name="Member">
      <Column Name="ID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Date_Joined" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>